version: '3.8'

services:
  api:
    build:
      context: ./MS_ROS_V0.1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: go run main.go
    networks:
      - my_network
  robot:
    image: javier8renero/tfg_ms:humble
    depends_on:
      - api
    # Por si en vez de hacer un pull, quiere compilar la imagen en local, decomentar todos lo build
    # build:
    #   context: ./Docker
    #   dockerfile: Dockerfile
    # !! En caso de ejecutarlo en windows descomentar las siguientes lineas
    # environment:
    #   - DISPLAY=host.docker.internal:0.0
    #   - LIBGL_ALWAYS_INDIRECT=0
    #   - TURTLEBOT3_MODEL=waffle_pi
    environment:
      - DISPLAY=$DISPLAY
      - TERM=$TERM
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - TURTLEBOT3_MODEL=waffle_pi
    volumes:
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
    devices:
      - /dev/dri:/dev/dri
    command: ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py 
    networks:
      - my_network
   
  ms_autocontrol: 
    # build:
    #   context: ./Docker
    #   dockerfile: Dockerfile
    networks:
      - my_network
    privileged: true
    image: javier8renero/tfg_ms:humble
    depends_on:
      - robot
    command: ros2 run turtlebot3_gazebo turtlebot3_drive
   
  ms_battery_publisher:
    # build:
    #   context: ./Docker
    #   dockerfile: Dockerfile
    networks:
      - my_network
    privileged: true
    image: javier8renero/tfg_ms:humble
    depends_on:
      - robot
      - ms_autocontrol
    command: ros2 run ms_sub battery_publisher
  ms_odm:
    # build:
    #   context: ./Docker
    #   dockerfile: Dockerfile
    networks:
      - my_network
    privileged: true
    image: javier8renero/tfg_ms:humble
    depends_on:
      - robot
      - ms_autocontrol
    ports:
      - 5001:5001
    command: ros2 run ms_sub odom_suscriber

  ms_battery_subscriber:
    # build:
    #   context: ./Docker
    #   dockerfile: Dockerfile
    networks:
      - my_network
    privileged: true
    image: javier8renero/tfg_ms:humble
    command: ros2 run ms_sub battery_subscriber
    depends_on:
      - robot
      - ms_autocontrol
    ports:
      - 5000:5000
networks:
  my_network:
    driver: bridge
    

