version: '3.4'

services:
  api:
    build:
      context: ./MS_ROS_V0.1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: go run main.go
    networks:
      - my_network
  ms_odm:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
   # volumes:
     # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      #- /tmp/.docker.xauth:/tmp/.docker.xauth
    networks:
      - my_network
    privileged: true
    image: javier8renero/tfg_ms:humble
    tty: true
    ports:
      - 5001:5001
    #command: ros2 run ms_sub odm_subscriber
  robot:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
   # volumes:
     # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      #- /tmp/.docker.xauth:/tmp/.docker.xauth
    networks:
      - my_network
    privileged: true
    image: javier8renero/tfg_ms:humble
    tty: true
    #command: export TURTLEBOT3_MODEL=waffle_pi && ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py

  ms_autocontrol:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
   # volumes:
     # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      #- /tmp/.docker.xauth:/tmp/.docker.xauth
    networks:
      - my_network
    privileged: true
    image: javier8renero/tfg_ms:humble
    tty: true
    #command: ros2 run turtlebot3_gazebo turtlebot3_drive
   
  ms_battery_publisher:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
   # volumes:
     # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      #- /tmp/.docker.xauth:/tmp/.docker.xauth
    networks:
      - my_network
    privileged: true
    image: javier8renero/tfg_ms:humble
    tty: true
    #command: ros2 run ms_sub battery_publisher
    
  ms_battery_subscriber:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
   # volumes:
     # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      #- /tmp/.docker.xauth:/tmp/.docker.xauth
    networks:
      - my_network
    privileged: true
    image: javier8renero/tfg_ms:humble
    tty: true
    #command: ros2 run ms_sub battery_subscriber
    ports:
      - 5000:5000

networks:
  my_network:
    driver: bridge
    
