version: '3.4'

services:
  api:
    build:
      context: ./MS_ROS_V0.1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: go run main.go
    networks:
      - my_network
  robot:
    image: javier8renero/tfg_ms:humble
    depends_on:
      - api
    # build:
    #   context: ./Docker
    #   dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - TURTLEBOT3_MODEL=waffle_pi
    networks:
      - my_network
    command: ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py

  ms_autocontrol:
    # build:
    #   context: ./Docker
    #   dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    networks:
      - my_network
    privileged: true
    image: javier8renero/tfg_ms:humble
    depends_on:
      - robot
    command: ros2 run turtlebot3_gazebo turtlebot3_drive
   
  ms_battery_publisher:
    # build:
    #   context: ./Docker
    #   dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    networks:
      - my_network
    privileged: true
    image: javier8renero/tfg_ms:humble
    depends_on:
      - robot
    command: ros2 run ms_sub battery_publisher
  ms_odm:
    # build:
    #   context: ./Docker
    #   dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    networks:
      - my_network
    privileged: true
    image: javier8renero/tfg_ms:humble
    depends_on:
      - robot
    ports:
      - 5001:5001
    command: ros2 run ms_sub odom_suscriber

  ms_battery_subscriber:
    # build:
    #   context: ./Docker
    #   dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    networks:
      - my_network
    privileged: true
    image: javier8renero/tfg_ms:humble
    command: ros2 run ms_sub battery_subscriber
    depends_on:
      - robot
    ports:
      - 5000:5000

networks:
  my_network:
    driver: bridge
    
